import { Prisma } from "@prisma/client";

export interface UserCreateBody {
  MobilePrefix?: string;
  Mobile?: string;
  Name?: string;
  DharmaName?: string;
  MageNickname?: string;
  LineId?: string;
  Email?: string;
  IsMonk: boolean;
  StayIdentity?: string | number;
  IsMale: boolean;
  BirthDate?: Date;
  IdNumber?: string;
  PassportNumber?: string;
  BirthPlace?: string;
  Phone?: string;
  Ordination?: string;
  Altar?: string;
  ShavedMaster?: string;
  ShavedDate?: Date;
  OrdinationTemple?: string;
  OrdinationDate?: Date;
  ResidentialTemple?: string;
  RefugueMaster?: string;
  RefugueDate?: Date;
  Referrer?: string;
  ClothType?: number;
  ClothSize?: string;
  EmergencyName?: string;
  EmergencyPhone?: string;
  Relationship?: string;
  Expertise?: Prisma.NullableJsonNullValueInput | Prisma.InputJsonValue;
  Education?: string;
  ComeTempleReason?: string;
  HealthStatus?: Prisma.NullableJsonNullValueInput | Prisma.InputJsonValue;
  EatBreakfast?: boolean;
  EatLunch?: boolean;
  EatDinner?: boolean;
  Address?: Prisma.NullableJsonNullValueInput | Prisma.InputJsonValue;
  Remarks?: string;
}
