name: Donglin temple BE CD

on: workflow_call

jobs:
  cd-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: donglin-temple-BE-ci.yml
          workflow_conclusion: success
      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}
