name: Donglin temple BE CD

on:
  workflow_run:
    workflows: [Donglin temple BE CI]
    types:
      - completed

jobs:
  cd-stage:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Download a Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: donglin-temple-BE-ci.yml
          workflow_conclusion: success
      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{}' \
          ${{ secrets.RENDER_DEPLOY_HOOK }}
