name: Donglin temple BE CI

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.18.2

      - name: Get pnpm cache & Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate PrismaClient
        run: pnpm prisma generate

      - name: Generate route and swagger file by Tsoa
        run: pnpm tsoa spec-and-routes

      - name: Lint code
        run: pnpm lint

      - name: Test code
        run: pnpm test

      - name: Build
        run: pnpm tsc -p tsconfig.json

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          name: donglin-temple-api-artifact
          path: |
            .
            !node_modules
  cd-stage:
    needs: ci-stage
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/donglin-temple-BE-cd.yml
